/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Gabriel
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JMenu = new javax.swing.JPanel();
        btnTiragem = new javax.swing.JButton();
        btnEncomenda = new javax.swing.JButton();
        btnAddFuncionario = new javax.swing.JButton();
        btnProfessor = new javax.swing.JButton();
        pnPrincipal = new javax.swing.JPanel();
        pnAddFuncionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnEncomenda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnTiragem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnProfessor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnTiragem.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnTiragem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impressora-de-porta-aberta-40.png"))); // NOI18N
        btnTiragem.setText("  TIRAGEM");
        btnTiragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiragemActionPerformed(evt);
            }
        });

        btnEncomenda.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnEncomenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-histórico-de-encomendas-40.png"))); // NOI18N
        btnEncomenda.setText("  ENCOMENDA");
        btnEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomendaActionPerformed(evt);
            }
        });

        btnAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-adicionar-usuário-masculino-48.png"))); // NOI18N
        btnAddFuncionario.setToolTipText("Adicionar novo funcionário");
        btnAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuncionarioActionPerformed(evt);
            }
        });

        btnProfessor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-live-folder-40.png"))); // NOI18N
        btnProfessor.setText("  PROFESSOR");
        btnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JMenuLayout = new javax.swing.GroupLayout(JMenu);
        JMenu.setLayout(JMenuLayout);
        JMenuLayout.setHorizontalGroup(
            JMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProfessor)
                .addGap(11, 11, 11)
                .addComponent(btnTiragem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncomenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(btnAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JMenuLayout.setVerticalGroup(
            JMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTiragem)
                        .addComponent(btnEncomenda)
                        .addComponent(btnProfessor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("painel de add funcionario");

        javax.swing.GroupLayout pnAddFuncionarioLayout = new javax.swing.GroupLayout(pnAddFuncionario);
        pnAddFuncionario.setLayout(pnAddFuncionarioLayout);
        pnAddFuncionarioLayout.setHorizontalGroup(
            pnAddFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddFuncionarioLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        pnAddFuncionarioLayout.setVerticalGroup(
            pnAddFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddFuncionarioLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jLabel2.setText("painel de encomenda");

        javax.swing.GroupLayout pnEncomendaLayout = new javax.swing.GroupLayout(pnEncomenda);
        pnEncomenda.setLayout(pnEncomendaLayout);
        pnEncomendaLayout.setHorizontalGroup(
            pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEncomendaLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel2)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        pnEncomendaLayout.setVerticalGroup(
            pnEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEncomendaLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel2)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jLabel3.setText("painel de tiragem");

        javax.swing.GroupLayout pnTiragemLayout = new javax.swing.GroupLayout(pnTiragem);
        pnTiragem.setLayout(pnTiragemLayout);
        pnTiragemLayout.setHorizontalGroup(
            pnTiragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTiragemLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel3)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        pnTiragemLayout.setVerticalGroup(
            pnTiragemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTiragemLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jLabel4.setText("painel de professor");

        javax.swing.GroupLayout pnProfessorLayout = new javax.swing.GroupLayout(pnProfessor);
        pnProfessor.setLayout(pnProfessorLayout);
        pnProfessorLayout.setHorizontalGroup(
            pnProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfessorLayout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnProfessorLayout.setVerticalGroup(
            pnProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfessorLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel4)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnTiragem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnEncomenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnTiragem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnEncomenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTiragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiragemActionPerformed
        
    }//GEN-LAST:event_btnTiragemActionPerformed

    private void btnEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomendaActionPerformed
        
    }//GEN-LAST:event_btnEncomendaActionPerformed

    private void btnAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuncionarioActionPerformed
      
    }//GEN-LAST:event_btnAddFuncionarioActionPerformed

    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JMenu;
    private javax.swing.JButton btnAddFuncionario;
    private javax.swing.JButton btnEncomenda;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnTiragem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnAddFuncionario;
    private javax.swing.JPanel pnEncomenda;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnProfessor;
    private javax.swing.JPanel pnTiragem;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAddFuncionario() {
        return btnAddFuncionario;
    }

    public JButton getBtnEncomenda() {
        return btnEncomenda;
    }

    public JButton getBtnProfessor() {
        return btnProfessor;
    }

    public JButton getBtnTiragem() {
        return btnTiragem;
    }

    public JPanel getPnAddFuncionario() {
        return pnAddFuncionario;
    }

    public JPanel getPnEncomenda() {
        return pnEncomenda;
    }

    public JPanel getPnPrincipal() {
        return pnPrincipal;
    }

    public JPanel getPnProfessor() {
        return pnProfessor;
    }

    public JPanel getPnTiragem() {
        return pnTiragem;
    }
}
