/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Gabriel
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public MainView() {
        initComponents();
        pnMenu.setBorder( new MatteBorder(0, 0, 0, 1, Color.gray));
        btnGroup.add(jrbTiragemAvulsa);
        btnGroup.add(jrbTiragemEncomendada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        pnPrincipal = new javax.swing.JPanel();
        pnInfoEncomenda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNomeEncomenda = new javax.swing.JTextField();
        btnSalvarEncomenda = new javax.swing.JButton();
        pnAvisaEncomendaSalva = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        pnTiragem = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jrbTiragemEncomendada = new javax.swing.JRadioButton();
        jrbTiragemAvulsa = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        pnSelecioneEncomenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListEncomenda = new javax.swing.JList();
        jcbSelecioneFuncionario = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtNomeTiragem = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtQtdTiragem = new javax.swing.JTextField();
        btnSalvarTiragem = new javax.swing.JButton();
        btnCancelarTiragem = new javax.swing.JButton();
        pnEncomenda = new javax.swing.JPanel();
        txtBairroCliente = new javax.swing.JTextField();
        lblNumeroCliente = new javax.swing.JLabel();
        txtNumeroCliente = new javax.swing.JTextField();
        lblCidadeCliente = new javax.swing.JLabel();
        txtNomeCidadeCliente = new javax.swing.JTextField();
        lblCepCliente = new javax.swing.JLabel();
        lblEstadoCliente = new javax.swing.JLabel();
        txtNomeEstadoCliente = new javax.swing.JTextField();
        lblUfCliente = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        txtPaisCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        lblPaisCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblCpfCliente = new javax.swing.JLabel();
        lblTelefoneCliente = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblRuaCliente = new javax.swing.JLabel();
        btnProximoPanelCliente = new javax.swing.JButton();
        txtRuaCliente = new javax.swing.JTextField();
        btnLimparCliente = new javax.swing.JButton();
        lblBairroCliente = new javax.swing.JLabel();
        btnCancelarCliente = new javax.swing.JButton();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        txtTelefoneCliente = new javax.swing.JFormattedTextField();
        txtCepCliente = new javax.swing.JFormattedTextField();
        txtUfCliente = new javax.swing.JFormattedTextField();
        pnProfessor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnAddFuncionario = new javax.swing.JPanel();
        lblNomeFuncionario = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmailFuncionario = new javax.swing.JLabel();
        lblCpfFuncionario = new javax.swing.JLabel();
        lblTelefoneFuncionario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRuaFuncionario = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblBairroFuncionario = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblNumeroFuncionario = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCidadeFuncionario = new javax.swing.JLabel();
        txtNomeCidade = new javax.swing.JTextField();
        lblCepFuncionario = new javax.swing.JLabel();
        lblEstadoFuncionario = new javax.swing.JLabel();
        txtNomeEstado = new javax.swing.JTextField();
        lblUfFuncionario = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        lblPaisFuncionario = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        txtUf = new javax.swing.JFormattedTextField();
        pnMenu = new javax.swing.JPanel();
        btnAddFuncionario = new javax.swing.JButton();
        btnProfessor = new javax.swing.JButton();
        btnTiragem = new javax.swing.JButton();
        btnEncomenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pnPrincipal.setLayout(null);

        pnInfoEncomenda.setPreferredSize(new java.awt.Dimension(359, 359));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("INFORMAÇÕES DA ENCOMENDA");

        jLabel30.setText("Nome da encomenda");

        txtNomeEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEncomendaActionPerformed(evt);
            }
        });

        btnSalvarEncomenda.setText("Salvar encomenda");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Pronto! A encomenda foi salva com sucesso");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Agora vá em ");

        jLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impressora-de-porta-aberta-40.png"))); // NOI18N
        jLabel33.setText("  Tiragem");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText(" e faça as tiragens relacionadas");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("a esta encomenda.");

        javax.swing.GroupLayout pnAvisaEncomendaSalvaLayout = new javax.swing.GroupLayout(pnAvisaEncomendaSalva);
        pnAvisaEncomendaSalva.setLayout(pnAvisaEncomendaSalvaLayout);
        pnAvisaEncomendaSalvaLayout.setHorizontalGroup(
            pnAvisaEncomendaSalvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAvisaEncomendaSalvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAvisaEncomendaSalvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel35)
                    .addGroup(pnAvisaEncomendaSalvaLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnAvisaEncomendaSalvaLayout.setVerticalGroup(
            pnAvisaEncomendaSalvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAvisaEncomendaSalvaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(pnAvisaEncomendaSalvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnInfoEncomendaLayout = new javax.swing.GroupLayout(pnInfoEncomenda);
        pnInfoEncomenda.setLayout(pnInfoEncomendaLayout);
        pnInfoEncomendaLayout.setHorizontalGroup(
            pnInfoEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInfoEncomendaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(121, 121, 121))
            .addGroup(pnInfoEncomendaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pnAvisaEncomendaSalva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnInfoEncomendaLayout.createSequentialGroup()
                .addGroup(pnInfoEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInfoEncomendaLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(btnSalvarEncomenda))
                    .addGroup(pnInfoEncomendaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnInfoEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(txtNomeEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnInfoEncomendaLayout.setVerticalGroup(
            pnInfoEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInfoEncomendaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEncomenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSalvarEncomenda)
                .addGap(53, 53, 53)
                .addComponent(pnAvisaEncomendaSalva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPrincipal.add(pnInfoEncomenda);
        pnInfoEncomenda.setBounds(-18, -15, 490, 460);

        pnTiragem.setPreferredSize(new java.awt.Dimension(359, 359));
        pnTiragem.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("REALIZAR TIRAGEM");
        pnTiragem.add(jLabel36);
        jLabel36.setBounds(169, 11, 144, 17);

        jrbTiragemEncomendada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbTiragemEncomendada.setText("Uma tiragem relacionada a alguma encomenda.");
        pnTiragem.add(jrbTiragemEncomendada);
        jrbTiragemEncomendada.setBounds(20, 80, 283, 23);

        jrbTiragemAvulsa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrbTiragemAvulsa.setText("Simplesmente uma tiragem avulsa.");
        pnTiragem.add(jrbTiragemAvulsa);
        jrbTiragemAvulsa.setBounds(20, 110, 213, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("A tiragem é de que tipo?");
        pnTiragem.add(jLabel3);
        jLabel3.setBounds(20, 60, 138, 15);

        ListEncomenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ListEncomenda.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListEncomenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListEncomenda.setToolTipText("Selecione aqui a encomenda");
        jScrollPane1.setViewportView(ListEncomenda);

        javax.swing.GroupLayout pnSelecioneEncomendaLayout = new javax.swing.GroupLayout(pnSelecioneEncomenda);
        pnSelecioneEncomenda.setLayout(pnSelecioneEncomendaLayout);
        pnSelecioneEncomendaLayout.setHorizontalGroup(
            pnSelecioneEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSelecioneEncomendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnSelecioneEncomendaLayout.setVerticalGroup(
            pnSelecioneEncomendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSelecioneEncomendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTiragem.add(pnSelecioneEncomenda);
        pnSelecioneEncomenda.setBounds(10, 138, 470, 160);

        jcbSelecioneFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnTiragem.add(jcbSelecioneFuncionario);
        jcbSelecioneFuncionario.setBounds(360, 330, 110, 20);

        jLabel37.setText("Selecione o funcionario");
        pnTiragem.add(jLabel37);
        jLabel37.setBounds(360, 310, 110, 14);

        jLabel38.setText("Nome da tiragem");
        pnTiragem.add(jLabel38);
        jLabel38.setBounds(20, 310, 110, 14);
        pnTiragem.add(txtNomeTiragem);
        txtNomeTiragem.setBounds(20, 330, 200, 20);

        jLabel39.setText("Quantidade de tiragens");
        pnTiragem.add(jLabel39);
        jLabel39.setBounds(20, 370, 140, 14);
        pnTiragem.add(txtQtdTiragem);
        txtQtdTiragem.setBounds(20, 390, 60, 20);

        btnSalvarTiragem.setText("Salvar tiragem");
        pnTiragem.add(btnSalvarTiragem);
        btnSalvarTiragem.setBounds(360, 430, 110, 23);

        btnCancelarTiragem.setText("Cancelar");
        pnTiragem.add(btnCancelarTiragem);
        btnCancelarTiragem.setBounds(270, 430, 80, 23);

        pnPrincipal.add(pnTiragem);
        pnTiragem.setBounds(-18, -15, 490, 460);

        pnEncomenda.setPreferredSize(new java.awt.Dimension(472, 435));
        pnEncomenda.setLayout(null);
        pnEncomenda.add(txtBairroCliente);
        txtBairroCliente.setBounds(40, 260, 190, 20);

        lblNumeroCliente.setText("Número*");
        pnEncomenda.add(lblNumeroCliente);
        lblNumeroCliente.setBounds(250, 240, 50, 14);
        pnEncomenda.add(txtNumeroCliente);
        txtNumeroCliente.setBounds(250, 260, 180, 20);

        lblCidadeCliente.setText("Cidade*");
        pnEncomenda.add(lblCidadeCliente);
        lblCidadeCliente.setBounds(40, 290, 60, 14);
        pnEncomenda.add(txtNomeCidadeCliente);
        txtNomeCidadeCliente.setBounds(40, 310, 190, 20);

        lblCepCliente.setText("CEP*");
        pnEncomenda.add(lblCepCliente);
        lblCepCliente.setBounds(250, 290, 40, 14);

        lblEstadoCliente.setText("Estado*");
        pnEncomenda.add(lblEstadoCliente);
        lblEstadoCliente.setBounds(40, 340, 60, 14);
        pnEncomenda.add(txtNomeEstadoCliente);
        txtNomeEstadoCliente.setBounds(40, 360, 89, 20);

        lblUfCliente.setText("UF*");
        pnEncomenda.add(lblUfCliente);
        lblUfCliente.setBounds(150, 340, 30, 14);

        lblNomeCliente.setText("Nome*");
        pnEncomenda.add(lblNomeCliente);
        lblNomeCliente.setBounds(40, 40, 40, 14);
        pnEncomenda.add(txtPaisCliente);
        txtPaisCliente.setBounds(250, 360, 180, 20);
        pnEncomenda.add(txtNomeCliente);
        txtNomeCliente.setBounds(40, 60, 390, 20);
        pnEncomenda.add(txtEmailCliente);
        txtEmailCliente.setBounds(40, 110, 390, 20);

        lblPaisCliente.setText("Pais*");
        pnEncomenda.add(lblPaisCliente);
        lblPaisCliente.setBounds(250, 340, 40, 14);

        lblEmailCliente.setText("Email*");
        pnEncomenda.add(lblEmailCliente);
        lblEmailCliente.setBounds(40, 90, 40, 14);

        lblCpfCliente.setText("CPF*");
        pnEncomenda.add(lblCpfCliente);
        lblCpfCliente.setBounds(40, 140, 160, 14);

        lblTelefoneCliente.setText("Telefone*");
        pnEncomenda.add(lblTelefoneCliente);
        lblTelefoneCliente.setBounds(250, 140, 60, 14);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("CADASTRAR NOVO CLIENTE");
        pnEncomenda.add(jLabel27);
        jLabel27.setBounds(116, 11, 202, 17);

        lblRuaCliente.setText("Rua*");
        pnEncomenda.add(lblRuaCliente);
        lblRuaCliente.setBounds(40, 190, 50, 14);

        btnProximoPanelCliente.setText("Próximo");
        btnProximoPanelCliente.setFocusPainted(false);
        pnEncomenda.add(btnProximoPanelCliente);
        btnProximoPanelCliente.setBounds(230, 400, 100, 22);
        pnEncomenda.add(txtRuaCliente);
        txtRuaCliente.setBounds(40, 210, 390, 20);

        btnLimparCliente.setText("Limpar");
        btnLimparCliente.setFocusPainted(false);
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });
        pnEncomenda.add(btnLimparCliente);
        btnLimparCliente.setBounds(350, 20, 80, 22);

        lblBairroCliente.setText("Bairro*");
        pnEncomenda.add(lblBairroCliente);
        lblBairroCliente.setBounds(40, 240, 50, 14);

        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.setFocusPainted(false);
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });
        pnEncomenda.add(btnCancelarCliente);
        btnCancelarCliente.setBounds(340, 400, 90, 22);

        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnEncomenda.add(txtCpfCliente);
        txtCpfCliente.setBounds(40, 160, 160, 20);

        try {
            txtTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnEncomenda.add(txtTelefoneCliente);
        txtTelefoneCliente.setBounds(250, 160, 177, 20);

        try {
            txtCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnEncomenda.add(txtCepCliente);
        txtCepCliente.setBounds(250, 310, 180, 20);

        try {
            txtUfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnEncomenda.add(txtUfCliente);
        txtUfCliente.setBounds(150, 360, 80, 20);

        pnPrincipal.add(pnEncomenda);
        pnEncomenda.setBounds(-18, -15, 490, 460);

        pnProfessor.setPreferredSize(new java.awt.Dimension(472, 435));

        jLabel4.setText("painel de professor");

        javax.swing.GroupLayout pnProfessorLayout = new javax.swing.GroupLayout(pnProfessor);
        pnProfessor.setLayout(pnProfessorLayout);
        pnProfessorLayout.setHorizontalGroup(
            pnProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfessorLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        pnProfessorLayout.setVerticalGroup(
            pnProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfessorLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel4)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pnPrincipal.add(pnProfessor);
        pnProfessor.setBounds(-18, -15, 490, 460);

        pnAddFuncionario.setPreferredSize(new java.awt.Dimension(472, 435));
        pnAddFuncionario.setLayout(null);

        lblNomeFuncionario.setText("Nome*");
        pnAddFuncionario.add(lblNomeFuncionario);
        lblNomeFuncionario.setBounds(50, 40, 60, 14);
        pnAddFuncionario.add(txtNome);
        txtNome.setBounds(50, 60, 390, 20);
        pnAddFuncionario.add(txtEmail);
        txtEmail.setBounds(50, 110, 390, 20);

        lblEmailFuncionario.setText("Email*");
        pnAddFuncionario.add(lblEmailFuncionario);
        lblEmailFuncionario.setBounds(50, 90, 50, 14);

        lblCpfFuncionario.setText("CPF*");
        pnAddFuncionario.add(lblCpfFuncionario);
        lblCpfFuncionario.setBounds(50, 140, 40, 14);

        lblTelefoneFuncionario.setText("Telefone*");
        pnAddFuncionario.add(lblTelefoneFuncionario);
        lblTelefoneFuncionario.setBounds(280, 140, 60, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRAR NOVO FUNCIONÁRIO");
        pnAddFuncionario.add(jLabel1);
        jLabel1.setBounds(114, 11, 245, 17);

        lblRuaFuncionario.setText("Rua*");
        pnAddFuncionario.add(lblRuaFuncionario);
        lblRuaFuncionario.setBounds(50, 190, 50, 14);
        pnAddFuncionario.add(txtRua);
        txtRua.setBounds(50, 210, 390, 20);

        lblBairroFuncionario.setText("Bairro*");
        pnAddFuncionario.add(lblBairroFuncionario);
        lblBairroFuncionario.setBounds(50, 240, 40, 14);
        pnAddFuncionario.add(txtBairro);
        txtBairro.setBounds(50, 260, 204, 20);

        lblNumeroFuncionario.setText("Número*");
        pnAddFuncionario.add(lblNumeroFuncionario);
        lblNumeroFuncionario.setBounds(270, 240, 60, 14);
        pnAddFuncionario.add(txtNumero);
        txtNumero.setBounds(270, 260, 172, 20);

        lblCidadeFuncionario.setText("Cidade*");
        pnAddFuncionario.add(lblCidadeFuncionario);
        lblCidadeFuncionario.setBounds(50, 290, 60, 14);
        pnAddFuncionario.add(txtNomeCidade);
        txtNomeCidade.setBounds(50, 310, 204, 20);

        lblCepFuncionario.setText("CEP*");
        pnAddFuncionario.add(lblCepFuncionario);
        lblCepFuncionario.setBounds(270, 290, 40, 14);

        lblEstadoFuncionario.setText("Estado*");
        pnAddFuncionario.add(lblEstadoFuncionario);
        lblEstadoFuncionario.setBounds(50, 340, 50, 14);
        pnAddFuncionario.add(txtNomeEstado);
        txtNomeEstado.setBounds(50, 360, 89, 20);

        lblUfFuncionario.setText("UF*");
        pnAddFuncionario.add(lblUfFuncionario);
        lblUfFuncionario.setBounds(160, 340, 50, 14);
        pnAddFuncionario.add(txtPais);
        txtPais.setBounds(270, 360, 172, 20);

        lblPaisFuncionario.setText("Pais*");
        pnAddFuncionario.add(lblPaisFuncionario);
        lblPaisFuncionario.setBounds(270, 340, 40, 14);

        btnSalvar.setText("Salvar");
        btnSalvar.setFocusPainted(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnAddFuncionario.add(btnSalvar);
        btnSalvar.setBounds(270, 400, 70, 22);

        btnLimpar.setText("Limpar");
        btnLimpar.setFocusPainted(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        pnAddFuncionario.add(btnLimpar);
        btnLimpar.setBounds(350, 30, 90, 22);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnAddFuncionario.add(btnCancelar);
        btnCancelar.setBounds(350, 400, 90, 22);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnAddFuncionario.add(txtCpf);
        txtCpf.setBounds(50, 160, 206, 20);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnAddFuncionario.add(txtTelefone);
        txtTelefone.setBounds(280, 160, 160, 20);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnAddFuncionario.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(270, 310, 172, 20);

        try {
            txtUf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnAddFuncionario.add(txtUf);
        txtUf.setBounds(160, 360, 97, 20);

        pnPrincipal.add(pnAddFuncionario);
        pnAddFuncionario.setBounds(-14, -12, 490, 460);

        getContentPane().add(pnPrincipal);
        pnPrincipal.setBounds(208, 11, 470, 448);

        pnMenu.setLayout(null);

        btnAddFuncionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-adicionar-usuário-masculino-48.png"))); // NOI18N
        btnAddFuncionario.setFocusPainted(false);
        btnAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuncionarioActionPerformed(evt);
            }
        });
        pnMenu.add(btnAddFuncionario);
        btnAddFuncionario.setBounds(10, 390, 70, 60);

        btnProfessor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-live-folder-40.png"))); // NOI18N
        btnProfessor.setText("  Professor");
        btnProfessor.setFocusPainted(false);
        btnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorActionPerformed(evt);
            }
        });
        pnMenu.add(btnProfessor);
        btnProfessor.setBounds(10, 40, 170, 60);

        btnTiragem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTiragem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-impressora-de-porta-aberta-40.png"))); // NOI18N
        btnTiragem.setText("  Tiragem");
        btnTiragem.setFocusPainted(false);
        btnTiragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiragemActionPerformed(evt);
            }
        });
        pnMenu.add(btnTiragem);
        btnTiragem.setBounds(10, 120, 170, 60);

        btnEncomenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEncomenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-histórico-de-encomendas-40.png"))); // NOI18N
        btnEncomenda.setText("  Encomenda");
        btnEncomenda.setFocusPainted(false);
        btnEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncomendaActionPerformed(evt);
            }
        });
        pnMenu.add(btnEncomenda);
        btnEncomenda.setBounds(10, 200, 170, 60);

        getContentPane().add(pnMenu);
        pnMenu.setBounds(0, 0, 192, 560);

        setSize(new java.awt.Dimension(694, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFuncionarioActionPerformed

    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfessorActionPerformed

    private void btnTiragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTiragemActionPerformed

    private void btnEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncomendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncomendaActionPerformed

    private void txtNomeEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEncomendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEncomendaActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListEncomenda;
    private javax.swing.JButton btnAddFuncionario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnCancelarTiragem;
    private javax.swing.JButton btnEncomenda;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnProximoPanelCliente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarEncomenda;
    private javax.swing.JButton btnSalvarTiragem;
    private javax.swing.JButton btnTiragem;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbSelecioneFuncionario;
    private javax.swing.JRadioButton jrbTiragemAvulsa;
    private javax.swing.JRadioButton jrbTiragemEncomendada;
    private javax.swing.JLabel lblBairroCliente;
    private javax.swing.JLabel lblBairroFuncionario;
    private javax.swing.JLabel lblCepCliente;
    private javax.swing.JLabel lblCepFuncionario;
    private javax.swing.JLabel lblCidadeCliente;
    private javax.swing.JLabel lblCidadeFuncionario;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblCpfFuncionario;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEmailFuncionario;
    private javax.swing.JLabel lblEstadoCliente;
    private javax.swing.JLabel lblEstadoFuncionario;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblNumeroCliente;
    private javax.swing.JLabel lblNumeroFuncionario;
    private javax.swing.JLabel lblPaisCliente;
    private javax.swing.JLabel lblPaisFuncionario;
    private javax.swing.JLabel lblRuaCliente;
    private javax.swing.JLabel lblRuaFuncionario;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JLabel lblTelefoneFuncionario;
    private javax.swing.JLabel lblUfCliente;
    private javax.swing.JLabel lblUfFuncionario;
    private javax.swing.JPanel pnAddFuncionario;
    private javax.swing.JPanel pnAvisaEncomendaSalva;
    private javax.swing.JPanel pnEncomenda;
    private javax.swing.JPanel pnInfoEncomenda;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnProfessor;
    private javax.swing.JPanel pnSelecioneEncomenda;
    private javax.swing.JPanel pnTiragem;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairroCliente;
    private javax.swing.JFormattedTextField txtCepCliente;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCidade;
    private javax.swing.JTextField txtNomeCidadeCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeEncomenda;
    private javax.swing.JTextField txtNomeEstado;
    private javax.swing.JTextField txtNomeEstadoCliente;
    private javax.swing.JTextField txtNomeTiragem;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroCliente;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPaisCliente;
    private javax.swing.JTextField txtQtdTiragem;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtRuaCliente;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTelefoneCliente;
    private javax.swing.JFormattedTextField txtUf;
    private javax.swing.JFormattedTextField txtUfCliente;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAddFuncionario() {
        return btnAddFuncionario;
    }

    public JButton getBtnEncomenda() {
        return btnEncomenda;
    }

    public JButton getBtnProfessor() {
        return btnProfessor;
    }

    public JButton getBtnTiragem() {
        return btnTiragem;
    }

    public JPanel getPnAddFuncionario() {
        return pnAddFuncionario;
    }

    public JPanel getPnEncomenda() {
        return pnEncomenda;
    }

    public JPanel getPnPrincipal() {
        return pnPrincipal;
    }

    public JPanel getPnProfessor() {
        return pnProfessor;
    }

    public JPanel getPnTiragem() {
        return pnTiragem;
    }

    public JTextField getTxtBairro() {
        return txtBairro;
    }

    public JFormattedTextField getTxtCep() {
        return jFormattedTextField1;
    }

    public JFormattedTextField getTxtCpf() {
        return txtCpf;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public JTextField getTxtNomeCidade() {
        return txtNomeCidade;
    }

    public JTextField getTxtNomeEstado() {
        return txtNomeEstado;
    }

    public JTextField getTxtNumero() {
        return txtNumero;
    }

    public JTextField getTxtPais() {
        return txtPais;
    }

    public JTextField getTxtRua() {
        return txtRua;
    }

    public JFormattedTextField getTxtTelefone() {
        return txtTelefone;
    }

    public JFormattedTextField getTxtUf() {
        return txtUf;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnLimpar() {
        return btnLimpar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JPanel getPnMenu() {
        return pnMenu;
    }

    public JButton getBtnCancelarCliente() {
        return btnCancelarCliente;
    }

    public JButton getBtnLimparCliente() {
        return btnLimparCliente;
    }

    public JButton getBtnProximoPanelCliente() {
        return btnProximoPanelCliente;
    }

    public JPanel getPnInfoEncomenda() {
        return pnInfoEncomenda;
    }

    public JTextField getTxtBairroCliente() {
        return txtBairroCliente;
    }

    public JFormattedTextField getTxtCepCliente() {
        return txtCepCliente;
    }

    public JFormattedTextField getTxtCpfCliente() {
        return txtCpfCliente;
    }

    public JTextField getTxtEmailCliente() {
        return txtEmailCliente;
    }

    public JTextField getTxtNomeCidadeCliente() {
        return txtNomeCidadeCliente;
    }

    public JTextField getTxtNomeCliente() {
        return txtNomeCliente;
    }

    public JTextField getTxtNomeEstadoCliente() {
        return txtNomeEstadoCliente;
    }

    public JTextField getTxtNumeroCliente() {
        return txtNumeroCliente;
    }

    public JTextField getTxtPaisCliente() {
        return txtPaisCliente;
    }

    public JTextField getTxtRuaCliente() {
        return txtRuaCliente;
    }

    public JFormattedTextField getTxtTelefoneCliente() {
        return txtTelefoneCliente;
    }

    public JFormattedTextField getTxtUfCliente() {
        return txtUfCliente;
    }

    public JButton getBtnSalvarEncomenda() {
        return btnSalvarEncomenda;
    }

    public JTextField getTxtNomeEncomenda() {
        return txtNomeEncomenda;
    }   

    public JPanel getPnAvisaEncomendaSalva() {
        return pnAvisaEncomendaSalva;
    }

    public JLabel getLblBairroFuncionario() {
        return lblBairroFuncionario;
    }

    public void setLblBairroFuncionario(JLabel lblBairroFuncionario) {
        this.lblBairroFuncionario = lblBairroFuncionario;
    }

    public JLabel getLblCepFuncionario() {
        return lblCepFuncionario;
    }

    public void setLblCepFuncionario(JLabel lblCepFuncionario) {
        this.lblCepFuncionario = lblCepFuncionario;
    }

    public JLabel getLblCidadeFuncionario() {
        return lblCidadeFuncionario;
    }

    public void setLblCidadeFuncionario(JLabel lblCidadeFuncionario) {
        this.lblCidadeFuncionario = lblCidadeFuncionario;
    }

    public JLabel getLblCpfFuncionario() {
        return lblCpfFuncionario;
    }

    public void setLblCpfFuncionario(JLabel lblCpfFuncionario) {
        this.lblCpfFuncionario = lblCpfFuncionario;
    }

    public JLabel getLblEmailFuncionario() {
        return lblEmailFuncionario;
    }

    public void setLblEmailFuncionario(JLabel lblEmailFuncionario) {
        this.lblEmailFuncionario = lblEmailFuncionario;
    }

    public JLabel getLblEstadoFuncionario() {
        return lblEstadoFuncionario;
    }

    public void setLblEstadoFuncionario(JLabel lblEstadoFuncionario) {
        this.lblEstadoFuncionario = lblEstadoFuncionario;
    }

    public JLabel getLblNomeFuncionario() {
        return lblNomeFuncionario;
    }

    public void setLblNomeFuncionario(JLabel lblNomeFuncionario) {
        this.lblNomeFuncionario = lblNomeFuncionario;
    }

    public JLabel getLblNumeroFuncionario() {
        return lblNumeroFuncionario;
    }

    public void setLblNumeroFuncionario(JLabel lblNumeroFuncionario) {
        this.lblNumeroFuncionario = lblNumeroFuncionario;
    }

    public JLabel getLblPaisFuncionario() {
        return lblPaisFuncionario;
    }

    public void setLblPaisFuncionario(JLabel lblPaisFuncionario) {
        this.lblPaisFuncionario = lblPaisFuncionario;
    }

    public JLabel getLblRuaFuncionario() {
        return lblRuaFuncionario;
    }

    public void setLblRuaFuncionario(JLabel lblRuaFuncionario) {
        this.lblRuaFuncionario = lblRuaFuncionario;
    }

    public JLabel getLblTelefoneFuncionario() {
        return lblTelefoneFuncionario;
    }

    public void setLblTelefoneFuncionario(JLabel lblTelefoneFuncionario) {
        this.lblTelefoneFuncionario = lblTelefoneFuncionario;
    }

    public JLabel getLblUfFuncionario() {
        return lblUfFuncionario;
    }

    public void setLblUfFuncionario(JLabel lblUfFuncionario) {
        this.lblUfFuncionario = lblUfFuncionario;
    }

    public JLabel getLblBairroCliente() {
        return lblBairroCliente;
    }

    public void setLblBairroCliente(JLabel lblBairroCliente) {
        this.lblBairroCliente = lblBairroCliente;
    }

    public JLabel getLblCepCliente() {
        return lblCepCliente;
    }

    public void setLblCepCliente(JLabel lblCepCliente) {
        this.lblCepCliente = lblCepCliente;
    }

    public JLabel getLblCidadeCliente() {
        return lblCidadeCliente;
    }

    public void setLblCidadeCliente(JLabel lblCidadeCliente) {
        this.lblCidadeCliente = lblCidadeCliente;
    }

    public JLabel getLblCpfCliente() {
        return lblCpfCliente;
    }

    public void setLblCpfCliente(JLabel lblCpfCliente) {
        this.lblCpfCliente = lblCpfCliente;
    }

    public JLabel getLblEmailCliente() {
        return lblEmailCliente;
    }

    public void setLblEmailCliente(JLabel lblEmailCliente) {
        this.lblEmailCliente = lblEmailCliente;
    }

    public JLabel getLblEstadoCliente() {
        return lblEstadoCliente;
    }

    public void setLblEstadoCliente(JLabel lblEstadoCliente) {
        this.lblEstadoCliente = lblEstadoCliente;
    }

    public JLabel getLblNomeCliente() {
        return lblNomeCliente;
    }

    public void setLblNomeCliente(JLabel lblNomeCliente) {
        this.lblNomeCliente = lblNomeCliente;
    }

    public JLabel getLblNumeroCliente() {
        return lblNumeroCliente;
    }

    public void setLblNumeroCliente(JLabel lblNumeroCliente) {
        this.lblNumeroCliente = lblNumeroCliente;
    }

    public JLabel getLblPaisCliente() {
        return lblPaisCliente;
    }

    public void setLblPaisCliente(JLabel lblPaisCliente) {
        this.lblPaisCliente = lblPaisCliente;
    }

    public JLabel getLblRuaCliente() {
        return lblRuaCliente;
    }

    public void setLblRuaCliente(JLabel lblRuaCliente) {
        this.lblRuaCliente = lblRuaCliente;
    }

    public JLabel getLblTelefoneCliente() {
        return lblTelefoneCliente;
    }

    public void setLblTelefoneCliente(JLabel lblTelefoneCliente) {
        this.lblTelefoneCliente = lblTelefoneCliente;
    }

    public JLabel getLblUfCliente() {
        return lblUfCliente;
    }

    public void setLblUfCliente(JLabel lblUfCliente) {
        this.lblUfCliente = lblUfCliente;
    }
    
    
    
}
